[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.master.environment]
  NODE_ENV = "prod"
  QUICKSILVER_API = "https://lcd.quicksilver.zone"
  ZONE_URL = "quicksilver.zone"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"

[context.test.environment]
  NODE_ENV = "test"
  QUICKSILVER_API = "https://lcd.test.quicksilver.zone"
  ZONE_URL = "test.quicksilver.zone"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"

[context.preprod.environment]
  NODE_ENV = "preprod"
  QUICKSILVER_API = "https://lcd.quicksilver.zone"
  ZONE_URL = "quicksilver.zone"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"

[context.develop.environment]
  NODE_ENV = "dev"
  QUICKSILVER_API = "https://lcd.dev.quicksilver.zone"
  ZONE_URL = "dev.quicksilver.zone"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"
