[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.master.environment]
  NODE_ENV = "prod"
  QUICKSILVER_API = "https://lcd.quicksilver.zone"
  ZONE_URL = "quicksilver.zone"
  REACT_APP_WHITELISTED_ZONES = "stargaze-1,cosmoshub-4,regen-1,osmosis-1,sommelier-3"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="false"
  APY_ZONES_ENDPOINT="https://chains.cosmos.directory"

[context.preprod.environment]
  NODE_ENV = "preprod"
  QUICKSILVER_API = "https://lcd.quicksilver.zone"
  ZONE_URL = "quicksilver.zone"
  REACT_APP_WHITELISTED_ZONES = "stargaze-1,cosmoshub-4,regen-1,osmosis-1,sommelier-3"
  REACT_APP_ENABLE_UNBONDING="false"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="false"
  APY_ZONES_ENDPOINT="https://chains.cosmos.directory"

[context.test.environment]
  NODE_ENV = "test"
  QUICKSILVER_API = "https://lcd.test.quicksilver.zone"
  ZONE_URL = "test.quicksilver.zone"
  REACT_APP_WHITELISTED_ZONES = "uni-6,elgafar-1,osmo-test-4,theta-testnet-001,regen-redwood-1"
  REACT_APP_ENABLE_UNBONDING="true"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"
  APY_ZONES_ENDPOINT="https://chains.cosmos.directory"

[context.develop.environment]
  NODE_ENV = "dev"
  QUICKSILVER_API = "https://lcd.dev.quicksilver.zone"
  ZONE_URL = "dev.quicksilver.zone"
  REACT_APP_WHITELISTED_ZONES = "quickstar-1,quickgaia-1,quickosmo-1"
  REACT_APP_ENABLE_UNBONDING="true"
  REACT_APP_ENABLE_SET_INTENT="false"
  REACT_APP_ENABLE_CLAIMS="true"
  APY_ZONES_ENDPOINT="https://chains.cosmos.directory"
